"""
API response models and authentication tokens.
"""

from typing import Optional
from pydantic import BaseModel, Field


class TokenResponse(BaseModel):
    """OAuth2 Access Token response from WHO Access Management."""
    access_token: str
    token_type: str = "Bearer"
    expires_in: int
    scope: Optional[str] = None


class ValidationReport(BaseModel):
    """Report generated by the validator service."""
    missing_names: int = 0
    missing_codes: int = 0
    duplicate_ids: int = 0
    broken_hierarchy: int = 0
    circular_references: int = 0
    missing_parents: int = 0
    missing_children: int = 0
    duplicate_synonyms: int = 0
    total_entities_validated: int = 0
    is_valid: bool = True
    details: list = Field(default_factory=list)
